In [1]:
# pandas
import pandas as pd

verificar = 'hashlist10.txt' #nome do arquivo para colocar na variavel teste
historicoarquivo = 'Historico.txt' #nome do arquivo para colocar na variavel historico
colspecs = [(0,32),(32,34),(34,-1)]
historico = pd.read_fwf(historicoarquivo,colspecs = colspecs, names=['hashmd5sum','sp','arquivo'] )
teste = pd.read_fwf(verificar,colspecs = colspecs, names=['hashmd5sum','sp','arquivo'] )

display(teste)

comparado_tem = teste[teste['hashmd5sum'].isin(list(historico['hashmd5sum']))]
display(comparado_tem)

comparado_naotem = teste[~teste['hashmd5sum'].isin(list(historico['hashmd5sum']))]
display(comparado_naotem)

                            hashmd5sum sp                  arquivo
0     d1d6e995a74e9b2dd6037eb5a157c8eb  *  IMG-20220425-WA0000.jpg
1     ea6b85b5ce356b06bf9542b1cc1b1f72  *  IMG-20220425-WA0003.jpg
2     70f7b26ccfd68ceecd26e9752b27cd23  *  IMG-20220425-WA0007.jpg
3     9d87049609f7f7ddd318ff77a77f4789  *  IMG-20220425-WA0102.jpg
4     84444391c59ed4ba3abb50329671ee42  *  IMG-20220425-WA0198.jpg
...                                ... ..                      ...
1948  88e0f48dabd89924b5656d9e6a7b7b92  *  VID-20220426-WA0804.mp4
1949  8cc2b562e5059604c32504c25819b9b0  *  VID-20220426-WA0805.mp4
1950  7c9380772cf02698ad406202ac6ad0df  *  VID-20220426-WA0806.mp4
1951  3ff1e6edbf43532fdd74b521afe64744  *  VID-20220426-WA0807.mp4
1952  732042e7bc1e8a0bdd6e31ca1703733a  *  VID-20220426-WA0808.mp4

[1953 rows x 3 columns]

                            hashmd5sum sp                  arquivo
0     d1d6e995a74e9b2dd6037eb5a157c8eb  *  IMG-20220425-WA0000.jpg
141   99abf6658d77b51f86380e0f46832bd7  *  IMG-20220426-WA0203.jpg
146   da403e028f76971d2e215a15c8476f57  *  IMG-20220426-WA0208.jpg
147   16590af8aae9a139f94aa903dd65fbb0  *  IMG-20220426-WA0209.jpg
152   48a5a32194fa154da3ec3cd7d26373b9  *  IMG-20220426-WA0214.jpg
...                                ... ..                      ...
1899  6a4dad46c6e275fce53dcb1fc9756955  *  VID-20220426-WA0755.mp4
1900  549644a13799b5cfdaa51050a1c1e928  *  VID-20220426-WA0756.mp4
1913  ef581f0dfb2c84c0ce9be2adb81da9a8  *  VID-20220426-WA0769.mp4
1930  ef5e3c8b8312c6d5984d84271106f1af  *  VID-20220426-WA0786.mp4
1932  79b031bf3ae2740c2aeec70fb11de8ac  *  VID-20220426-WA0788.mp4

[361 rows x 3 columns]

                            hashmd5sum sp                  arquivo
1     ea6b85b5ce356b06bf9542b1cc1b1f72  *  IMG-20220425-WA0003.jpg
2     70f7b26ccfd68ceecd26e9752b27cd23  *  IMG-20220425-WA0007.jpg
3     9d87049609f7f7ddd318ff77a77f4789  *  IMG-20220425-WA0102.jpg
4     84444391c59ed4ba3abb50329671ee42  *  IMG-20220425-WA0198.jpg
5     70f32af74917ec8fae88ad4caeec03bc  *  IMG-20220425-WA0199.jpg
...                                ... ..                      ...
1948  88e0f48dabd89924b5656d9e6a7b7b92  *  VID-20220426-WA0804.mp4
1949  8cc2b562e5059604c32504c25819b9b0  *  VID-20220426-WA0805.mp4
1950  7c9380772cf02698ad406202ac6ad0df  *  VID-20220426-WA0806.mp4
1951  3ff1e6edbf43532fdd74b521afe64744  *  VID-20220426-WA0807.mp4
1952  732042e7bc1e8a0bdd6e31ca1703733a  *  VID-20220426-WA0808.mp4

[1592 rows x 3 columns]

In [2]:
comparado_tem['arquivo'].to_csv('listax.txt', index=False, header=False)
display(historico)
comparado_naotem['hashmd5sum'].to_csv('historico.txt', index=False, header=False, mode='a')
historico = pd.read_fwf('Historico.txt',colspecs = colspecs, names=['hashmd5sum','sp','arquivo'] )
display(historico)

                              hashmd5sum   sp                   arquivo
0       9eff7b4bda6e3e5ec6cc384701a748f7   ,*  ,IMG-20220112-WA1401.jpg
1       ee512d5748a6e5776b25b11ed6a25059   ,,                       NaN
2       33b6b0a1d465ae532b1a87e3ec054bdd   ,,                       NaN
3       8b734263bda75132f90f8c9940d1e165   ,,                       NaN
4       1296c4664b6d9e11db4ac82025c607b6   ,,                       NaN
...                                  ...  ...                       ...
112172  c52ad579bd0d3b0c8301fb2ede2c4775  NaN                       NaN
112173  c67d36de8d998f455dadc7fa963ae2db  NaN                       NaN
112174  4100ba36770fa03e981c4d03c31262b7  NaN                       NaN
112175  9561765d803b361af8ad55786e7aab1a  NaN                       NaN
112176  c8915312ed3975e576cdd24647639e71  NaN                       NaN

[112177 rows x 3 columns]

                              hashmd5sum   sp                   arquivo
0       9eff7b4bda6e3e5ec6cc384701a748f7   ,*  ,IMG-20220112-WA1401.jpg
1       ee512d5748a6e5776b25b11ed6a25059   ,,                       NaN
2       33b6b0a1d465ae532b1a87e3ec054bdd   ,,                       NaN
3       8b734263bda75132f90f8c9940d1e165   ,,                       NaN
4       1296c4664b6d9e11db4ac82025c607b6   ,,                       NaN
...                                  ...  ...                       ...
113764  88e0f48dabd89924b5656d9e6a7b7b92  NaN                       NaN
113765  8cc2b562e5059604c32504c25819b9b0  NaN                       NaN
113766  7c9380772cf02698ad406202ac6ad0df  NaN                       NaN
113767  3ff1e6edbf43532fdd74b521afe64744  NaN                       NaN
113768  732042e7bc1e8a0bdd6e31ca1703733a  NaN                       NaN

[113769 rows x 3 columns]

In [15]:
# historico.hashmd5sum.duplicated()
# historico.hashmd5sum.duplicated().sum() # soma de duplicados
# (~historico.hashmd5sum.duplicated()).sum() # soma de NAO duplicados
# historico.loc[historico.duplicated(), :] # lista duplicados
# historico.drop_duplicates(inplace=True) # remove duplicados do dataframe, sem o inplace cria novo dataframe

# Considering certain columns for dropping duplicates
# df.drop_duplicates(subset=['Survived', 'Pclass', 'Sex'])

# To drop all duplicates
# df.drop_duplicates(keep=False)

# Use keep='last' to keep the last occurrence 
# df.drop_duplicates(keep='last')
historico.info()
historico.hashmd5sum.duplicated().sum()

# print (historico)
# historico.to_csv('historico.txt', index=False, header=False)
historico.to_csv('historico_A.txt', index=False, header=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 105746 entries, 0 to 105746
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   hashmd5sum  105746 non-null  object
 1   sp          2 non-null       object
 2   arquivo     2 non-null       object
dtypes: object(3)
memory usage: 3.2+ MB

In [13]:
import os
import hashlib
from tqdm import tqdm #pip3 install --target="C:\Program Files\Python310\Scripts" tqdm ;cmd como ADM

path = '/Users/raziel/Python/018-hashlist_csv'
files = os.listdir(path)
# pbar = tqdm(total=len(path), position=0, leave=True)

for cadaarquivo in files:
    md5_hash = hashlib.md5()
    with open(cadaarquivo,"rb") as f:
        # Read and update hash in chunks of 4K
        for byte_block in iter(lambda: f.read(4096),b""):
            md5_hash.update(byte_block)
        print(md5_hash.hexdigest())

PermissionError: [Errno 13] Permission denied: '.ipynb_checkpoints'

In [22]:

from tqdm import tqdm
from pathlib import Path
 
 
#for i in tqdm(range(int(9e6))):
#    pass


from tqdm import tqdm
from time import sleep
 
#for i in tqdm(range(0, 100), desc ="Text You Want"):
#    sleep(.1)
    
#for i in tqdm(range(0, 100), ncols = 100, position = 0,
#               desc ="Text You Want"):
#    sleep(.1)

caminho = Path.cwd()
print(caminho)
pbar = tqdm(total=len(caminho), position=0, leave=True)

arquivos = caminho.iterdir()
for cadaarquivo in arquivos:
    print(cadaarquivo)
    sleep(.1)

C:\Users\raziel\Python\018-hashlist_csv

TypeError: object of type 'WindowsPath' has no len()