In [9]:
# pandas
import pandas as pd

verificar = 'hashlist10.txt' #nome do arquivo para colocar na variavel teste
historicoarquivo = 'Historico_A.txt' #nome do arquivo para colocar na variavel historico
colspecs = [(0,32),(32,34),(34,-1)]
historico = pd.read_fwf(historicoarquivo,colspecs = colspecs, names=['hashmd5sum','sp','arquivo'] )
teste = pd.read_fwf(verificar,colspecs = colspecs, names=['hashmd5sum','sp','arquivo'] )

display(teste)

comparado_tem = teste[teste['hashmd5sum'].isin(list(historico['hashmd5sum']))]
display(comparado_tem)

comparado_naotem = teste[~teste['hashmd5sum'].isin(list(historico['hashmd5sum']))]
display(comparado_naotem)

                            hashmd5sum sp                  arquivo
0     b7496fab02b607784aaf7523d073c1b9  *  IMG-20220419-WA0239.jpg
1     faa3b4f3a9a474a1d568820f98e6f7ff  *  IMG-20220419-WA0277.jpg
2     7d7b4706d0828f837ef211415e35770d  *  IMG-20220419-WA0352.jpg
3     8a4e676d248a591bfb0e868328fcf264  *  IMG-20220419-WA0368.jpg
4     72a3f5370d80d6932688d4c3999a6cea  *  IMG-20220419-WA0369.jpg
...                                ... ..                      ...
2589  e586b27537a2a68592fbbfbb16dc6f09  *  VID-20220419-WA3440.mp4
2590  265151a5a37e295dd040a0c7cc4fef2c  *  VID-20220419-WA3441.mp4
2591  8a5a2b15ca57d2c0ed4950ec936af1aa  *  VID-20220419-WA3442.mp4
2592  0c26b507b069bb84763d47692499d015  *  VID-20220419-WA3443.mp4
2593  d647c3b4562ba1a9964ecc660bc2141e  *  VID-20220419-WA3445.mp4

[2594 rows x 3 columns]

                            hashmd5sum sp                  arquivo
27    10fb5590320bb02bf5665231f2c24692  *  IMG-20220419-WA0952.jpg
28    106d4d88e17c37d675b379d6c1aaa3c7  *  IMG-20220419-WA0953.jpg
105   3e8a74140d8e7d8321a4a9cb97d3a36b  *  IMG-20220419-WA1220.jpg
106   7211b03ef9102b31001b9bd94b509d32  *  IMG-20220419-WA1221.jpg
107   013ea485402d281bf8ecce623887544f  *  IMG-20220419-WA1222.jpg
...                                ... ..                      ...
2560  a07c11f15d0ef15e3e78abd166426aac  *  VID-20220419-WA3411.mp4
2563  6deee7514053f388a82f77f79758b6cc  *  VID-20220419-WA3414.mp4
2582  4f7155ab746bcf35e75d3846b1682203  *  VID-20220419-WA3433.mp4
2584  aed1d3583b15da280249e31f7ce499cc  *  VID-20220419-WA3435.mp4
2591  8a5a2b15ca57d2c0ed4950ec936af1aa  *  VID-20220419-WA3442.mp4

[670 rows x 3 columns]

                            hashmd5sum sp                  arquivo
0     b7496fab02b607784aaf7523d073c1b9  *  IMG-20220419-WA0239.jpg
1     faa3b4f3a9a474a1d568820f98e6f7ff  *  IMG-20220419-WA0277.jpg
2     7d7b4706d0828f837ef211415e35770d  *  IMG-20220419-WA0352.jpg
3     8a4e676d248a591bfb0e868328fcf264  *  IMG-20220419-WA0368.jpg
4     72a3f5370d80d6932688d4c3999a6cea  *  IMG-20220419-WA0369.jpg
...                                ... ..                      ...
2588  e3c480110d18df0cbb0be26a343bf45f  *  VID-20220419-WA3439.mp4
2589  e586b27537a2a68592fbbfbb16dc6f09  *  VID-20220419-WA3440.mp4
2590  265151a5a37e295dd040a0c7cc4fef2c  *  VID-20220419-WA3441.mp4
2592  0c26b507b069bb84763d47692499d015  *  VID-20220419-WA3443.mp4
2593  d647c3b4562ba1a9964ecc660bc2141e  *  VID-20220419-WA3445.mp4

[1924 rows x 3 columns]

In [10]:
comparado_tem['arquivo'].to_csv('listax.txt', index=False, header=False)
display(historico)
comparado_naotem['hashmd5sum'].to_csv('historico_A.txt', index=False, header=False, mode='a')
historico = pd.read_fwf('Historico_A.txt',colspecs = colspecs, names=['hashmd5sum','sp','arquivo'] )
display(historico)

                              hashmd5sum   sp                  arquivo
0       9eff7b4bda6e3e5ec6cc384701a748f7    *  IMG-20220112-WA1401.jpg
1       ee512d5748a6e5776b25b11ed6a25059  NaN                      NaN
2       33b6b0a1d465ae532b1a87e3ec054bdd  NaN                      NaN
3       8b734263bda75132f90f8c9940d1e165  NaN                      NaN
4       1296c4664b6d9e11db4ac82025c607b6  NaN                      NaN
...                                  ...  ...                      ...
103818  311aec8ab309ff0143c5a345a99cba9a  NaN                      NaN
103819  6bd726126b425dc8b160dec9e821416e  NaN                      NaN
103820  853cd88accc7c2031b9025787718b1ed  NaN                      NaN
103821  671ed59083bebff4d422d126fb7d0510  NaN                      NaN
103822  f51e290914592871c9dab0098b2307e4  NaN                      NaN

[103823 rows x 3 columns]

                              hashmd5sum   sp                  arquivo
0       9eff7b4bda6e3e5ec6cc384701a748f7    *  IMG-20220112-WA1401.jpg
1       ee512d5748a6e5776b25b11ed6a25059  NaN                      NaN
2       33b6b0a1d465ae532b1a87e3ec054bdd  NaN                      NaN
3       8b734263bda75132f90f8c9940d1e165  NaN                      NaN
4       1296c4664b6d9e11db4ac82025c607b6  NaN                      NaN
...                                  ...  ...                      ...
105742  e3c480110d18df0cbb0be26a343bf45f  NaN                      NaN
105743  e586b27537a2a68592fbbfbb16dc6f09  NaN                      NaN
105744  265151a5a37e295dd040a0c7cc4fef2c  NaN                      NaN
105745  0c26b507b069bb84763d47692499d015  NaN                      NaN
105746  d647c3b4562ba1a9964ecc660bc2141e  NaN                      NaN

[105747 rows x 3 columns]

In [15]:
# historico.hashmd5sum.duplicated()
# historico.hashmd5sum.duplicated().sum() # soma de duplicados
# (~historico.hashmd5sum.duplicated()).sum() # soma de NAO duplicados
# historico.loc[historico.duplicated(), :] # lista duplicados
# historico.drop_duplicates(inplace=True) # remove duplicados do dataframe, sem o inplace cria novo dataframe

# Considering certain columns for dropping duplicates
# df.drop_duplicates(subset=['Survived', 'Pclass', 'Sex'])

# To drop all duplicates
# df.drop_duplicates(keep=False)

# Use keep='last' to keep the last occurrence 
# df.drop_duplicates(keep='last')
historico.info()
historico.hashmd5sum.duplicated().sum()

# print (historico)
# historico.to_csv('historico.txt', index=False, header=False)
historico.to_csv('historico_A.txt', index=False, header=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 105746 entries, 0 to 105746
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   hashmd5sum  105746 non-null  object
 1   sp          2 non-null       object
 2   arquivo     2 non-null       object
dtypes: object(3)
memory usage: 3.2+ MB

In [13]:
import os
import hashlib
from tqdm import tqdm #pip3 install --target="C:\Program Files\Python310\Scripts" tqdm ;cmd como ADM

path = '/Users/raziel/Python/018-hashlist_csv'
files = os.listdir(path)
# pbar = tqdm(total=len(path), position=0, leave=True)

for cadaarquivo in files:
    md5_hash = hashlib.md5()
    with open(cadaarquivo,"rb") as f:
        # Read and update hash in chunks of 4K
        for byte_block in iter(lambda: f.read(4096),b""):
            md5_hash.update(byte_block)
        print(md5_hash.hexdigest())

PermissionError: [Errno 13] Permission denied: '.ipynb_checkpoints'

In [22]:

from tqdm import tqdm
from pathlib import Path
 
 
#for i in tqdm(range(int(9e6))):
#    pass


from tqdm import tqdm
from time import sleep
 
#for i in tqdm(range(0, 100), desc ="Text You Want"):
#    sleep(.1)
    
#for i in tqdm(range(0, 100), ncols = 100, position = 0,
#               desc ="Text You Want"):
#    sleep(.1)

caminho = Path.cwd()
print(caminho)
pbar = tqdm(total=len(caminho), position=0, leave=True)

arquivos = caminho.iterdir()
for cadaarquivo in arquivos:
    print(cadaarquivo)
    sleep(.1)

C:\Users\raziel\Python\018-hashlist_csv

TypeError: object of type 'WindowsPath' has no len()